apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: documentation
build:
  artifacts:
    - image: lcacollect/documentation
      sync:
        manual:
          - src: src/**/*.py
            dest: /app/src
            strip: src
        hooks:
          after:
            - container:
                command:
                  - bash
                  - /app/export_schema.sh
            - host:
                command:
                  - bash
                  - extract_schema.sh
                os:
                  - darwin
                  - linux
      docker:
        dockerfile: ./Dockerfile
        buildArgs:
          ARTIFACTS_TOKEN_BACKEND_PACKAGES: '{{ .ARTIFACTS_TOKEN_BACKEND_PACKAGES }}'
          BUILD_STAGE: DEV
          BUILD_VERSION: DEV
manifests:
  helm:
    flags:
      upgrade:
        - --install
    releases:
      - name: documentation
        chartPath: helm
        namespace: documentation
        setValues:
          appDomain: localhost:4000
          appProtocol: http
          db.ssl: "false"
          deployType: DEV
          imageKey.registry: lcacollect/documentation
          imageKey.repository: lcacollect/documentation
          imageKey.tag: lcacollect/documentation
          storageBasePath: test
        setValueTemplates:
          backend.speckleTokenSecret.value: '{{ .SPECKLE_TOKEN }}'
          backend.storageAccountURL.value: '{{ .STORAGE_ACCOUNT_URL }}'
          backend.storageContainer.value: '{{ .STORAGE_CONTAINER }}'
          backend.storageSecret.value: '{{ .STORAGE_SECRET }}'
        createNamespace: true
deploy:
  helm: { }

portForward:
  - resourceType: service
    resourceName: backend-service
    namespace: documentation
    port: 8000
    localPort: 4000
  - resourceType: service
    resourceName: database-service
    namespace: documentation
    port: 5432
    localPort: 5435
