"""empty message

Revision ID: 253c20ec6d5a
Revises: c66b6eb6dde5
Create Date: 2022-10-26 11:39:51.607082

"""
import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision = "253c20ec6d5a"
down_revision = "c66b6eb6dde5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tag",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("author_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("added", sa.Date(), nullable=False),
        sa.Column("commit_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["commit_id"],
            ["commit.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tag")
    # ### end Alembic commands ###
