"""empty message

Revision ID: 403525acbdd6
Revises: 46fc2ada8c87
Create Date: 2023-06-28 13:51:44.029863

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "403525acbdd6"
down_revision = "46fc2ada8c87"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("schemaelement", sa.Column("assembly_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("schemaelement", "assembly_id")
    # ### end Alembic commands ###
