"""empty message

Revision ID: 4793e7af27f7
Revises: b4cc2175c7d0
Create Date: 2022-10-20 10:37:37.443589

"""
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "4793e7af27f7"
down_revision = "b4cc2175c7d0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projectsource",
        sa.Column(
            "interpretation", postgresql.JSON(astext_type=sa.Text()), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projectsource", "interpretation")
    # ### end Alembic commands ###
