"""empty message

Revision ID: 4b4246ed9644
Revises: da450d4d89cf
Create Date: 2023-10-04 16:02:57.383384

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "4b4246ed9644"
down_revision = "da450d4d89cf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("typecodeelement", sa.Column("parent_path", sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column("typecodeelement", "code")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("typecodeelement", sa.Column("code", sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column("typecodeelement", "parent_path")
    # ### end Alembic commands ###
