"""empty message

Revision ID: 552c63c090ed
Revises: 5c8ffb30e8e0
Create Date: 2022-11-21 09:12:15.128794

"""
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "552c63c090ed"
down_revision = "5c8ffb30e8e0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "schemaelement",
        sa.Column("result", postgresql.JSON(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("schemaelement", "result")
    # ### end Alembic commands ###
