"""empty message

Revision ID: 5c8ffb30e8e0
Revises: 54ca42dc1db2
Create Date: 2022-11-16 12:39:03.383768

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "5c8ffb30e8e0"
down_revision = "54ca42dc1db2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "reportingschema",
        sa.Column("template_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "schematemplate",
        sa.Column("original_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.drop_constraint("schematemplate_schema_id_fkey", "schematemplate", type_="foreignkey")
    op.create_foreign_key(
        "schematemplate_schema_original_id_fkey",
        "schematemplate",
        "reportingschema",
        ["original_id"],
        ["id"],
    )
    op.drop_column("schematemplate", "schema_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "schematemplate",
        sa.Column("schema_id", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_constraint("schematemplate_schema_original_id_fkey", "schematemplate", type_="foreignkey")
    op.create_foreign_key(
        "schematemplate_schema_id_fkey",
        "schematemplate",
        "reportingschema",
        ["schema_id"],
        ["id"],
    )
    op.drop_column("schematemplate", "original_id")
    op.drop_column("reportingschema", "template_id")
    # ### end Alembic commands ###
