"""empty message

Revision ID: 74b203c08b1f
Revises: aeb2d81da286
Create Date: 2022-11-30 16:10:00.171836

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '74b203c08b1f'
down_revision = 'aeb2d81da286'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schemaelement', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('schemaelement', 'quantity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schemaelement', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('schemaelement', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
