"""empty message

Revision ID: 90adf54af5ad
Revises: da450d4d89cf
Create Date: 2023-10-06 09:29:25.612219

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "90adf54af5ad"
down_revision = "da450d4d89cf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "typecodeelement",
        sa.Column("parent_path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("typecodeelement", "parent_path")
    # ### end Alembic commands ###
