"""empty message

Revision ID: 9a2d2db37774
Revises: 403525acbdd6
Create Date: 2023-06-30 11:08:08.439099

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9a2d2db37774'
down_revision = '403525acbdd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schemaelement', sa.Column('meta_fields', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schemaelement', 'meta_fields')
    # ### end Alembic commands ###
