"""empty message

Revision ID: aeb2d81da286
Revises: 552c63c090ed
Create Date: 2022-11-30 15:02:08.979588

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "aeb2d81da286"
down_revision = "552c63c090ed"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("schemaelement", "subclassification")
    op.drop_column("schemaelement", "classification")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("schemaelement", sa.Column("classification", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column("schemaelement", sa.Column("subclassification", sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
