"""empty message

Revision ID: b4cc2175c7d0
Revises: fed2f0bb630b
Create Date: 2022-10-17 15:30:40.879288

"""
import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision = "b4cc2175c7d0"
down_revision = "fed2f0bb630b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "task",
        sa.Column("category_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        "task",
        sa.Column("element_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.alter_column("task", "status", existing_type=sa.VARCHAR(), nullable=True)
    op.create_foreign_key("fk_element", "task", "schemaelement", ["element_id"], ["id"])
    op.create_foreign_key(
        "fk_category", "task", "schemacategory", ["category_id"], ["id"]
    )
    op.drop_column("task", "item_type")
    op.drop_column("task", "item_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "task", sa.Column("item_id", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "task",
        sa.Column("item_type", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_constraint("fk_element", "task", type_="foreignkey")
    op.drop_constraint("fk_category", "task", type_="foreignkey")
    op.alter_column("task", "status", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("task", "element_id")
    op.drop_column("task", "category_id")
    # ### end Alembic commands ###
