"""empty message

Revision ID: bb2034b814ef
Revises: b30b3edb50aa
Create Date: 2022-10-07 16:20:50.453537

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "bb2034b814ef"
down_revision = "b30b3edb50aa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projectsource",
        sa.Column("meta_fields", postgresql.JSON(astext_type=sa.Text()), nullable=True),
    )
    op.add_column(
        "schemaelement",
        sa.Column("source_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.create_foreign_key("element_source_link", "schemaelement", "projectsource", ["source_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("element_source_link", "schemaelement", type_="foreignkey")
    op.drop_column("schemaelement", "source_id")
    op.drop_column("projectsource", "meta_fields")
    # ### end Alembic commands ###
