"""empty message

Revision ID: c362895ec441
Revises: c66b6eb6dde5
Create Date: 2022-10-26 12:49:59.835129

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "c362895ec441"
down_revision = "feec68cf12ce"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projectsource",
        sa.Column("author_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.add_column("projectsource", sa.Column("updated", sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projectsource", "updated")
    op.drop_column("projectsource", "author_id")
    # ### end Alembic commands ###
