"""empty message

Revision ID: e182d22faf5f
Revises: ffa2dd0245b2
Create Date: 2022-10-03 16:11:43.239732

"""
import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision = "e182d22faf5f"
down_revision = "ffa2dd0245b2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "repository",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "reporting_schema_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["reporting_schema_id"],
            ["reportingschema.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "commit",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("added", sa.Date(), nullable=False),
        sa.Column("short_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("parent_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("repository_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("author_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["commit.id"],
        ),
        sa.ForeignKeyConstraint(
            ["repository_id"],
            ["repository.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "categorycommitlink",
        sa.Column(
            "schema_category_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("commit_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["commit_id"],
            ["commit.id"],
        ),
        sa.ForeignKeyConstraint(
            ["schema_category_id"],
            ["schemacategory.id"],
        ),
        sa.PrimaryKeyConstraint("schema_category_id", "commit_id"),
    )
    op.create_table(
        "elementcommitlink",
        sa.Column(
            "schema_element_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("commit_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["commit_id"],
            ["commit.id"],
        ),
        sa.ForeignKeyConstraint(
            ["schema_element_id"],
            ["schemaelement.id"],
        ),
        sa.PrimaryKeyConstraint("schema_element_id", "commit_id"),
    )
    op.add_column(
        "schemacategory",
        sa.Column("project_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("schemacategory", "project_id")
    op.drop_table("elementcommitlink")
    op.drop_table("categorycommitlink")
    op.drop_table("commit")
    op.drop_table("repository")
    # ### end Alembic commands ###
