"""empty message

Revision ID: f0a2b62bfe5a
Revises: c362895ec441
Create Date: 2022-11-02 13:50:00.705941

"""
import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision = "f0a2b62bfe5a"
down_revision = "c362895ec441"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projectsource",
        sa.Column("data_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.drop_column("projectsource", "source_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projectsource",
        sa.Column("source_id", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("projectsource", "data_id")
    # ### end Alembic commands ###
