"""empty message

Revision ID: fed2f0bb630b
Revises: bb2034b814ef
Create Date: 2022-10-17 11:55:05.133692

"""
import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision = "fed2f0bb630b"
down_revision = "bb2034b814ef"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "projectsource", "source_id", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "projectsource", "source_id", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###
