"""empty message

Revision ID: feec68cf12ce
Revises: 253c20ec6d5a
Create Date: 2022-10-27 13:18:43.693641

"""
import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision = "feec68cf12ce"
down_revision = "253c20ec6d5a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tag", sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tag", "name")
    # ### end Alembic commands ###
