name: Container CI/CD Workflow

on:
  push:
    branches:
      - main
      - stage
  pull_request:
    branches:
      - main
      - stage
  workflow_dispatch:

jobs:
  test:
    uses: lcacollect/.github/.github/workflows/test-python.yaml@main
  publish-schema:
    if: github.event_name != 'pull_request'
    uses: lcacollect/.github/.github/workflows/publish-graphql.yaml@main
    needs: test
    with:
      name: 'documentation'
      branch: ${{ github.ref_name }}
      storage-account: ${{ vars.PRODUCTION_STORAGE_ACCOUNT }}
      container-name: ${{ vars.GRAPHQL_CONTAINER_NAME }}
    secrets:
      azure-credentials: ${{ secrets.AZURE_CREDENTIALS }}
  build-container:
    uses: lcacollect/.github/.github/workflows/build-image.yaml@main
    needs: test
    with:
      tag: "${{ github.run_number }}${{ (github.ref_name != 'main' && '-dev') || ''}}"
      registry: "lcacollect"
      name: 'documentation'
  publish-chart:
    if: github.event_name != 'pull_request'
    uses: lcacollect/.github/.github/workflows/publish-chart.yaml@main
    needs:
      - test
      - build-container
    with:
      tag: "${{ github.run_number }}${{ (github.ref_name != 'main' && '-dev') || ''}}"
      registry: "lcacollect"
      name: 'documentation'
  webhook:
    if: github.event_name != 'pull_request'
    needs:
      - publish-schema
      - publish-chart
    runs-on: ubuntu-latest
    permissions:
      repository-projects: read
      contents: write
    steps:
      - name: "Send Webhook"
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/lcacollect/router-backend/dispatches \
            -d '{"event_type":"workflow_completed","client_payload":{"branch":"${{ github.ref_name}}", "repo":"documentation"}}'